/* Dizionario italiano. Parole per tema, separate da spazio. */
const ITA_DICT = {
  work:"riunione progetto scrivania contratto fattura cliente scadenza report agenda badge stampante schermo tastiera codice server rete ufficio cartella documento firma timbro fascicolo dossier mansione turno pausa caffe verbale preventivo bilancio archivio collega capo stipendio bonifico ricevuta calendario lavagna telefono",
  home:"porta finestra tetto scala chiave lampada tavolo sedia letto cuscino armadio cassetto divano tappeto tenda specchio cucina forno frigo lavandino doccia balcone soffitta cantina corridoio camino mensola quadro vaso candela tovaglia coperta scaffale maniglia citofono campanello soglia ripostiglio garage",
  nature:"sole luna mare monte fiume lago bosco fiore albero vento neve pioggia stella nuvola prato roccia onda sabbia ghiaccio tuono fulmine alba tramonto nebbia rugiada cascata sentiero collina valle scogliera deserto palude foresta torrente seme foglia ramo radice",
  food:"pane mela pasta riso miele latte pizza formaggio oliva basilico limone ciliegia pera uva fico noce zucca patata carota cipolla aglio sale pepe burro brodo zuppa farina lievito crosta fetta torta gelato cioccolato biscotto marmellata insalata pomodoro",
  hobby:"chitarra pennello scacchi racchetta pallone bicicletta fotocamera romanzo modellino giardino pesca corsa nuoto scalata cucito ceramica origami acquerello tamburo flauto violino dado mazzo puzzle telescopio canna remo tenda zaino bussola mappa diario fumetto vinile cavalletto",
  tech:"resistore saldatore circuito sensore motore scheda cavo batteria filamento ugello condensatore transistor diodo antenna bobina morsetto dissipatore ventola modulo attuatore encoder stampante telaio cinghia puleggia vite dado rondella cuscinetto tester piano asse pinza chip memoria processore",
  animals:"gatto cane lupo volpe orso gufo ape pesce cavallo falco riccio talpa lontra cervo lepre topo corvo merlo rondine vespa ragno squalo balena delfino polpo granchio gambero aquila tasso furetto donnola scoiattolo cinghiale capriolo airone gabbiano",
  travel:"valigia mappa treno aereo biglietto passaporto albergo spiaggia citta confine dogana binario molo faro porto bussola sentiero rifugio tenda zaino borraccia souvenir cartolina frontiera traghetto vagone scalo terminal pedaggio autostrada",
  personal:"famiglia amico sorella fratello nonno sogno ricordo abbraccio sorriso viaggio lettera foto diario compleanno promessa segreto desiderio speranza coraggio pazienza affetto saluto regalo festa storia nome cuore mente anima respiro silenzio musica risata"
};
